markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Gaolz
url: http://gaowanxing.com
description: A fantastic blog that is fantastic.
twitter: Gaolz
